In [144]:
# %load 'validate_poi.py'


In [145]:
"""
    Starter code for the validation mini-project.
    The first step toward building your POI identifier!

    Start by loading/formatting the data

    After that, it's not our code anymore--it's yours!
"""

import pickle
import sys
sys.path.append("../tools/")
from feature_format import featureFormat, targetFeatureSplit

data_dict = pickle.load(open("../final_project/final_project_dataset.pkl", "rb") )

### first element is our labels, any added elements are predictor
### features. Keep this the same for the mini-project, but you'll
### have a different feature list when you do the final project.
features_list = ["poi", "salary"]

data = featureFormat(data_dict, features_list)
labels, features = targetFeatureSplit(data)

## types van datasets

In [146]:
#print een Python dictionary  (=JSON object  uit JSON-array)
data_dict["PRENTICE JAMES"]

{'salary': 'NaN',
 'to_messages': 'NaN',
 'deferral_payments': 564348,
 'total_payments': 564348,
 'loan_advances': 'NaN',
 'bonus': 'NaN',
 'email_address': 'james.prentice@enron.com',
 'restricted_stock_deferred': 'NaN',
 'deferred_income': 'NaN',
 'total_stock_value': 1095040,
 'expenses': 'NaN',
 'from_poi_to_this_person': 'NaN',
 'exercised_stock_options': 886231,
 'from_messages': 'NaN',
 'other': 'NaN',
 'from_this_person_to_poi': 'NaN',
 'poi': False,
 'long_term_incentive': 'NaN',
 'shared_receipt_with_poi': 'NaN',
 'restricted_stock': 208809,
 'director_fees': 'NaN'}

In [147]:
type(data_dict)

dict

In [148]:
type(data)

numpy.ndarray

In [149]:
len(data_dict)

146

In [156]:
#data_dict

In [151]:
# convert dict to dataframe
import pandas as pd
hond = pd.DataFrame.from_dict(data)
hond.shape

(95, 2)

In [152]:
type(hond)

pandas.core.frame.DataFrame

In [153]:
hond.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       95 non-null     float64
 1   1       95 non-null     float64
dtypes: float64(2)
memory usage: 1.6 KB


In [161]:
# example: df.columns = [‘A’, ‘B’, ‘C’, ‘D’]
hond.columns = ['POI?', 'salary']

In [162]:
hond

POI?    salary
0    0.0  365788.0
1    0.0  267102.0
2    0.0  170941.0
3    1.0  243293.0
4    0.0  267093.0
..   ...       ...
90   0.0  330546.0
91   1.0  415189.0
92   0.0  265214.0
93   0.0  278601.0
94   1.0  274975.0

[95 rows x 2 columns]

In [167]:
type(features)

list

In [168]:
len(features)

95

In [183]:
# hiermee maak je van 'dict' een 'lists'  
zoet = list(features)[0:5]
zoet

[array([365788.]),
 array([267102.]),
 array([170941.]),
 array([243293.]),
 array([267093.])]

In [181]:
type(zoet)

list

In [176]:
joop = ['a', 'b']       # hiermee creeer je een 'list'
joop

['a', 'b']

In [179]:
list(features)[0]       ==> hiermee pak je de 1e list  uit het object

array([365788.])

In [184]:
#list(vals)[0].shape       #  hier creeer je een tuple   
koekje = list(features)[0].shape        #waarvan je shape kan krijgen
koekje

(1,)

In [185]:
type(koekje)

tuple

In [187]:
list?               # to view the docstring

Init signature: list(iterable=(), /)
Docstring:     
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.
Type:           type
Subclasses:     _HashedSeq, StackSummary, SList, _Accumulator, _ImmutableLineList, FormattedText, NodeList, _ExplodedList, Stack, _ymd, ...


In [192]:
len(labels)

95

In [188]:
sum(labels)              #  dus 17 van 95 zijn een PersonOfInterest

17.0

In [ ]:
from sklearn.model_selection import cross_validate             #from sklearn import cross_validation
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

## Your first overfit POI identifier
Did you run a decision tree classifier with the default parameters on the full data? Remember that we're looking at the performance of the overfit tree first.

In [193]:
clf_overfit = DecisionTreeClassifier()

In [194]:
clf_overfit = clf_overfit.fit(features, labels)

In [195]:
prediction_overfit = clf_overfit.predict(features)
print ("Accuracy : ", accuracy_score(prediction_overfit, labels))

Accuracy :  0.9894736842105263


Pretty high accuracy, huh?  Yet another case where testing on the training data would make you think you were doing amazingly well, but as you already know, that's exactly what holdout test data is for...

## Deploying a Training/Testing Regime
Tried using splitting data into test/train

In [211]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size = 0.3, random_state=42)

In [212]:
len(X_train)

66

In [213]:
 len(X_test)

29

In [214]:
clf = DecisionTreeClassifier()

In [215]:
clf = clf.fit(X_train, y_train)

In [216]:
prediction = clf.predict(X_test)

In [217]:
print ("Accuracy : ", accuracy_score(prediction, y_test))

Accuracy :  0.6896551724137931


Aaaand the testing data brings us back down to earth after that 99% accuracy in the last quiz.

In [218]:
prediction

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.])